"""
フォントファイル構築モジュール．

生成されたグリフ画像（ラスターデータ）をベクター化し，
fontTools ライブリを用いて TrueType（TTF）または OpenType（OTF/CFF）形式の
フォントファイルを構築する．
"""

import re
import subprocess
import tempfile
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from pathlib import Path

from PIL import Image

try:
    from fontTools.fontBuilder import FontBuilder as FTFontBuilder
    from fontTools.pens.t2CharStringPen import T2CharStringPen
    from fontTools.ttLib import TTFont

    FONTTOOLS_AVAILABLE = True
except ImportError:
    FONTTOOLS_AVAILABLE = False


@dataclass
class FontMetadata:
    """フォントの名称やメトリクス情報を保持するデータクラス．"""

    family_name: str = "MojaiFont"
    style_name: str = "Regular"
    version: str = "1.0"
    copyright: str = "Generated by mojai"
    designer: str = ""

    # フォントメトリクスの定義（標準的な 1000 units/em 構成）
    units_per_em: int = 1000
    ascender: int = 800
    descender: int = -200
    line_gap: int = 0


@dataclass
class GlyphData:
    """個別のグリフ（文字）に関する情報を保持するデータクラス．"""

    character: str
    unicode_codepoint: int
    image: Image.Image | None = None
    svg_path: str = ""
    path_commands: list = field(default_factory=list)


class SVGPathParser:
    """
    SVG パスデータの解析を担当するクラス．

    Potrace 等で生成された SVG ファイルから 'd' 属性のパスコマンドを抽出・トークン化する．
    """

    @staticmethod
    def parse_svg_file(svg_path: Path) -> list[tuple]:
        """
        SVG ファイルからパスコマンドを抽出する．

        Args:
            svg_path (Path): 入力 SVG ファイルのパス．

        Returns:
            list[tuple]: コマンドと座標のリスト [(command, points), ...]．
        """
        try:
            tree = ET.parse(svg_path)
            root = tree.getroot()

            # XML 名前空間の考慮
            ns = {"svg": "http://www.w3.org/2000/svg"}

            # <path> エレメントの検索
            paths = root.findall(".//svg:path", ns)
            if not paths:
                paths = root.findall(".//path")

            all_commands = []
            for path in paths:
                d = path.get("d", "")
                commands = SVGPathParser.parse_path_data(d)
                all_commands.extend(commands)

            return all_commands

        except Exception as e:
            print(f"⚠️ SVG parsing error: {e}")
            return []

    @staticmethod
    def parse_path_data(d: str) -> list[tuple]:
        """
        SVG パス文字列（d属性）をパースして，構造化されたコマンドリストに変換する．
        """
        commands = []

        # アルファベット（コマンド）と数値（座標）を抽出
        token_pattern = re.compile(r"([MLHVCSQTAZmlhvcsqtaz])|(-?\d+\.?\d*)")
        tokens = token_pattern.findall(d)

        current_command = None
        current_points = []

        for token in tokens:
            cmd, num = token
            if cmd:
                if current_command:
                    commands.append((current_command, current_points))
                current_command = cmd
                current_points = []
            elif num:
                current_points.append(float(num))

        if current_command:
            commands.append((current_command, current_points))

        return commands


class FontBuilder:
    """
    フォント構築エンジンクラス．

    Potrace によるベクター化プロセスと，fontTools を用いたバイナリ構築を統括する．
    """

    def __init__(self, metadata: FontMetadata | None = None):
        """
        フォントビルダーを初期化する．

        Args:
            metadata (FontMetadata, optional): フォント名等の定義情報．
        """
        self.metadata = metadata or FontMetadata()
        self._glyphs: dict[str, GlyphData] = {}
        self._svg_parser = SVGPathParser()

    def add_glyph(self, character: str, image: Image.Image | Path | str) -> None:
        """
        特定の文字と画像のペアをグリフリストに追加する．
        """
        if isinstance(image, (Path, str)):
            img = Image.open(image)
        else:
            img = image

        if img.mode != "L":
            img = img.convert("L")

        glyph = GlyphData(
            character=character,
            unicode_codepoint=ord(character),
            image=img,
        )
        self._glyphs[character] = glyph

    def vectorize_glyph(self, glyph: GlyphData, output_svg: Path) -> bool:
        """
        外部ツール Potrace を呼び出し，グリフ画像をベクター形式（SVG）に変換する．

        Potrace が利用できない場合は，自動的に OpenCV ベースの輪郭抽出フォールバックを実行する．
        """
        if glyph.image is None:
            return False

        # Potrace は PBM 形式を要求するため，一時ファイルを生成する
        with tempfile.NamedTemporaryFile(suffix=".pbm", delete=False) as tmp:
            tmp_path = Path(tmp.name)
            # 128 を閾値として二値化し，PBM(mode="1") で保存
            binary = glyph.image.point(lambda x: 0 if x > 128 else 255, mode="1")
            binary.save(tmp_path)

        try:
            # Potrace の実行: SVG 出力，平滑化閾値などの最適化引数を指定
            subprocess.run(
                [
                    "potrace",
                    "-s",  # SVG 出力モード
                    "-t",
                    "5",  # 許容公差
                    "-o",
                    str(output_svg),
                    str(tmp_path),
                ],
                capture_output=True,
                check=True,
            )
            glyph.svg_path = str(output_svg)
            glyph.path_commands = self._svg_parser.parse_svg_file(output_svg)
            return True

        except (subprocess.CalledProcessError, FileNotFoundError):
            # Potrace 未インストール等の場合は OpenCV で代用
            return self._fallback_vectorize(glyph, output_svg)

        finally:
            tmp_path.unlink(missing_ok=True)

    def _fallback_vectorize(self, glyph: GlyphData, output_svg: Path) -> bool:
        """OpenCV の輪郭検出を用いた，シンプルなベクター化フォールバック．"""
        import cv2
        import numpy as np

        img_array = np.array(glyph.image)
        _, binary = cv2.threshold(img_array, 128, 255, cv2.THRESH_BINARY_INV)

        # 輪郭（Contours）の抽出
        contours, _ = cv2.findContours(binary, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

        width, height = glyph.image.size
        svg_paths = []

        for contour in contours:
            if len(contour) < 3:
                continue
            points = contour.squeeze()
            if len(points.shape) == 1:
                continue

            # 直線（L）コマンドによるパス形成
            path_data = f"M {points[0][0]} {points[0][1]} "
            for point in points[1:]:
                path_data += f"L {point[0]} {point[1]} "
            path_data += "Z"
            svg_paths.append(path_data)

        # SVG 文字列の構築
        svg_content = f'<?xml version="1.0" encoding="UTF-8"?>\n<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">\n'
        for path_data in svg_paths:
            svg_content += f'  <path d="{path_data}" fill="black"/>\n'
        svg_content += "</svg>"

        output_svg.write_text(svg_content)
        glyph.svg_path = str(output_svg)

        glyph.path_commands = []
        for path_data in svg_paths:
            glyph.path_commands.extend(self._svg_parser.parse_path_data(path_data))

        return True

    def build(self, output_path: Path | str) -> Path:
        """
        蓄積された全グリフをまとめ，バイナリフォントファイルを生成する．
        """
        output_path = Path(output_path)
        if not FONTTOOLS_AVAILABLE:
            raise RuntimeError("fontTools library is not installed.")

        # 作業用の一時ディレクトリでベクター化を全文字実行
        with tempfile.TemporaryDirectory() as tmp_dir:
            tmp_path = Path(tmp_dir)
            for char, glyph in self._glyphs.items():
                svg_path = tmp_path / f"U+{ord(char):04X}.svg"
                self.vectorize_glyph(glyph, svg_path)

            return self._build_font(output_path)

    def _build_font(self, output_path: Path) -> Path:
        """fontTools ライブリを用いて，各テーブルを設定しフォントをバイナリ化する．"""
        is_ttf = output_path.suffix.lower() == ".ttf"

        # FontBuilder の初期化（units/em 指定）
        fb = FTFontBuilder(self.metadata.units_per_em, isTTF=is_ttf)

        # グリフセットと Unicode マッピング（cmap）の定義
        glyph_order = [".notdef", "space"]
        cmap = {32: "space"}

        for char, glyph in self._glyphs.items():
            glyph_name = f"uni{glyph.unicode_codepoint:04X}"
            glyph_order.append(glyph_name)
            cmap[glyph.unicode_codepoint] = glyph_name

        fb.setupGlyphOrder(glyph_order)
        fb.setupCharacterMap(cmap)

        # フォント名称（name テーブル）の設定
        fb.setupNameTable(
            {
                "familyName": self.metadata.family_name,
                "styleName": self.metadata.style_name,
                "version": f"Version {self.metadata.version}",
                "copyright": self.metadata.copyright,
            }
        )

        # メトリクス情報の反映
        fb.setupHead(unitsPerEm=self.metadata.units_per_em)
        fb.setupHhea(
            ascent=self.metadata.ascender,
            descent=self.metadata.descender,
            lineGap=self.metadata.line_gap,
        )

        # 文字幅（hmtx テーブル）の一括設定
        advance_widths = {
            name: (
                self.metadata.units_per_em // 2
                if name in (".notdef", "space")
                else self.metadata.units_per_em
            )
            for name in glyph_order
        }
        fb.setupHmtx(advance_widths)

        # アウトライン（glyf / CFF）の構築
        if is_ttf:
            self._build_ttf_glyphs(fb, glyph_order)
        else:
            self._build_cff_glyphs(fb, glyph_order)

        fb.setupOS2()
        fb.setupPost()

        # 出力
        output_path.parent.mkdir(parents=True, exist_ok=True)
        fb.font.save(str(output_path))
        print(f"📦 Font built successfully: {output_path}")

        return output_path

    def _build_ttf_glyphs(self, fb: FTFontBuilder, glyph_order: list[str]) -> None:
        """TrueType アウトライン（Quadratic curves）形式でグリフを構築する．"""
        from fontTools.ttLib.tables._g_l_y_f import Glyph

        pen_data = {".notdef": self._create_notdef_glyph(), "space": Glyph()}

        for glyph_name in glyph_order[2:]:
            char = chr(int(glyph_name[3:], 16))
            glyph = self._glyphs.get(char)
            pen_data[glyph_name] = self._path_to_ttf_glyph(glyph) if glyph else Glyph()

        fb.setupGlyf(pen_data)

    def _build_cff_glyphs(self, fb: FTFontBuilder, glyph_order: list[str]) -> None:
        """PostScript/CFF アウトライン（Cubic curves）形式でグリフを構築する．"""
        charstrings = {}

        # .notdef の描画
        pen = T2CharStringPen(self.metadata.units_per_em, None)
        pen.rect(100, 0, 300, 700)
        charstrings[".notdef"] = pen.getCharString()

        # space の描画（空）
        pen = T2CharStringPen(self.metadata.units_per_em, None)
        charstrings["space"] = pen.getCharString()

        for glyph_name in glyph_order[2:]:
            char = chr(int(glyph_name[3:], 16))
            glyph = self._glyphs.get(char)
            charstrings[glyph_name] = (
                self._path_to_cff_charstring(glyph)
                if glyph
                else T2CharStringPen(self.metadata.units_per_em, None).getCharString()
            )

        fb.setupCFF(
            nameStrings={"familyName": self.metadata.family_name},
            charStringsDict=charstrings,
            privateDict={},
        )

    def _create_notdef_glyph(self):
        """フォントに未対応文字が含まれる際に表示される矩形グリフを作成する．"""
        from fontTools.ttLib.tables._g_l_y_f import Glyph

        glyph = Glyph()
        glyph.numberOfContours = 1
        glyph.coordinates = [(100, 0), (400, 0), (400, 700), (100, 700)]
        glyph.flags = [1, 1, 1, 1]
        glyph.endPtsOfContours = [3]
        return glyph

    def _path_to_ttf_glyph(self, glyph_data: GlyphData):
        """SVG パスを TrueType グリフ形式（座標反転およびスケーリング）に変換する．"""
        from fontTools.ttLib.tables._g_l_y_f import Glyph

        glyph = Glyph()
        if not glyph_data.path_commands:
            return glyph

        coordinates, flags, end_pts = [], [], []
        current_x, current_y = 0.0, 0.0
        # 画像解像度（64px）からフォントユニット（units_per_em）への変換倍率
        scale = self.metadata.units_per_em / 64.0

        for cmd, points in glyph_data.path_commands:
            if cmd in ("M", "m"):
                if coordinates and (not end_pts or end_pts[-1] != len(coordinates) - 1):
                    end_pts.append(len(coordinates) - 1)

                if len(points) >= 2:
                    if cmd == "m":
                        current_x += points[0]
                        current_y += points[1]
                    else:
                        current_x, current_y = points[0], points[1]

                    # 座標系の変換: SVG (上原点) -> Font (下原点)
                    coordinates.append((int(current_x * scale), int((64 - current_y) * scale)))
                    flags.append(1)

            elif cmd in ("L", "l"):
                i = 0
                while i < len(points) - 1:
                    if cmd == "l":
                        current_x += points[i]
                        current_y += points[i + 1]
                    else:
                        current_x, current_y = points[i], points[i + 1]

                    coordinates.append((int(current_x * scale), int((64 - current_y) * scale)))
                    flags.append(1)
                    i += 2

            elif cmd in ("Z", "z"):
                if coordinates:
                    end_pts.append(len(coordinates) - 1)

        if not coordinates:
            return glyph

        if not end_pts or end_pts[-1] != len(coordinates) - 1:
            end_pts.append(len(coordinates) - 1)

        glyph.numberOfContours = len(end_pts)
        glyph.coordinates = coordinates
        glyph.flags = flags
        glyph.endPtsOfContours = end_pts
        return glyph

    def _path_to_cff_charstring(self, glyph_data: GlyphData):
        """SVG パスを CFF CharString（PostScript アウトライン）に変換する．"""
        pen = T2CharStringPen(self.metadata.units_per_em, None)
        if not glyph_data.path_commands:
            return pen.getCharString()

        current_x, current_y = 0.0, 0.0
        scale = self.metadata.units_per_em / 64.0

        for cmd, points in glyph_data.path_commands:
            if cmd in ("M", "m"):
                if len(points) >= 2:
                    if cmd == "m":
                        current_x += points[0]
                        current_y += points[1]
                    else:
                        current_x, current_y = points[0], points[1]
                    pen.moveTo((current_x * scale, (64 - current_y) * scale))

            elif cmd in ("L", "l"):
                i = 0
                while i < len(points) - 1:
                    if cmd == "l":
                        current_x += points[i]
                        current_y += points[i + 1]
                    else:
                        current_x, current_y = points[i], points[i + 1]
                    pen.lineTo((current_x * scale, (64 - current_y) * scale))
                    i += 2

            elif cmd in ("C", "c"):
                # ベジェ曲線の描画
                i = 0
                while i < len(points) - 5:
                    if cmd == "c":
                        pts = [
                            (
                                (current_x + points[i + j]) * scale,
                                (64 - (current_y + points[i + j + 1])) * scale,
                            )
                            for j in range(0, 6, 2)
                        ]
                        current_x += points[i + 4]
                        current_y += points[i + 5]
                    else:
                        pts = [
                            (points[i + j] * scale, (64 - points[i + j + 1]) * scale)
                            for j in range(0, 6, 2)
                        ]
                        current_x, current_y = points[i + 4], points[i + 5]

                    pen.curveTo(*pts)
                    i += 6

            elif cmd in ("Z", "z"):
                pen.closePath()

        return pen.getCharString()
